apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name | default "default-pvc-name" }}
  labels:
    app: nginx
spec:
  accessModes:
    - {{ .Values.pvc.accessModes | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage | default "1Gi" }}
