apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name | default "my-pvc" }}
  labels:
    {{- include "my-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessModes | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage | default "1Gi" }}
  {{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
  {{- if .Values.pvc.selector }}
  selector:
    matchLabels:
      {{- toYaml .Values.pvc.selector.matchLabels | nindent 6 }}
  {{- end }}
