replicaCount: 1

image:
  repository: nginx
  tag: 1.26.3
  pullPolicy: IfNotPresent

service:  # Changed this to lowercase
  type: NodePort
  port: 80

  pvc:
  name: my-pvc
  accessModes:
    - ReadWriteOnce
  storage: 1Gi

