apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--sonarqube
  labels:
    app: sonarqube
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 9000

