apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sonarqube
spec:
  type: {{ .Values.service.type }}
  selector:
    app: sonarqube
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000

